#!/usr/bin/env python
# encoding: utf-8

name = "Diels_alder_addition/groups"
shortDesc = ""
longDesc = """

"""

template(reactants=["Root"], products=["Six_Ring"], ownReverse=False)

reverse = "Retro_Diels_Alder_Addition"
reversible = True

reactantNum = 2

productNum = 1

autoGenerated = True

recipe(actions=[
    ['CHANGE_BOND', '*1', -1, '*2'],
    ['CHANGE_BOND', '*3', -0.5, '*4'],
    ['CHANGE_BOND', '*4', 0.5, '*5'],
    ['CHANGE_BOND', '*5', -0.5, '*6'],
    ['FORM_BOND', '*1', 1, '*3'],
    ['FORM_BOND', '*2', 1, '*6'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *3 Cb u0 {2,B} 
2 *4 Cb u0 {1,B} {3,B}
3 *5 Cb u0 {2,B} {4,B}
4 *6 Cb u0 {3,B} 
5 *1 Ct u0 {6,T}
6 *2 Ct u0 {5,T}
""",
    kinetics = None,
)

forbidden(
    label = "allene_avoid_doublecounting",
    group = 
"""
1 *2 Cdd u0
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzene_diene1",
    group = 
"""
1 *3 Cd u0 {2,D} {6,S}
2 *4 Cd u0 {1,D} {3,S}
3 *5 Cd u0 {2,S} {4,D}
4 *6 Cd u0 {3,D} {5,S}
5    Cd ux {4,S} {6,D}
6    Cd ux {1,S} {5,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzene_diene2",
    group = 
"""
1 *3 Cd u0 {2,D} {6,S}
2 *4 Cd u0 {1,D} {3,S}
3 *5 Cd u0 {2,S} {4,D}
4 *6 Cd u0 {3,D} {5,S}
5 *8 Cd ux {4,S} {6,D}
6 *7 Cd ux {1,S} {5,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzene_diene_partial1",
    group = 
"""
1 *3 Cd u0 {2,D} {6,S}
2 *4 Cd u0 {1,D} {3,S}
3    Cd ux {2,S} {4,D}
4    Cd ux {3,D} {5,S}
5    Cd ux {4,S} {6,D}
6    Cd ux {1,S} {5,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzene_diene_partial2",
    group = 
"""
1 *5 Cd u0 {2,D} {6,S}
2 *6 Cd u0 {1,D} {3,S}
3    Cd ux {2,S} {4,D}
4    Cd ux {3,D} {5,S}
5    Cd ux {4,S} {6,D}
6    Cd ux {1,S} {5,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzene_ene",
    group = 
"""
1 *1 Cd u0 {2,D} {6,S}
2 *2 Cd u0 {1,D} {3,S}
3    Cd ux {2,S} {4,D}
4    Cd ux {3,D} {5,S}
5    Cd ux {4,S} {6,D}
6    Cd ux {1,S} {5,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzene_monoSub1",
    group = 
"""
1 *3 Cd u0 {2,D} {6,S} {7,S}
2 *4 Cd u0 {1,D} {3,S}
3 *5 Cd u0 {2,S} {4,D}
4 *6 Cd u0 {3,D} {5,S} {8,S}
5 *7 Cd ux {4,S} {6,D}
6 *8 Cd ux {1,S} {5,D}
7    H  u0 {1,S}
8 *9 R  ux {4,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzene_monoSub2",
    group = 
"""
1 *3 Cd u0 {2,D} {5,S} {6,S}
2 *4 Cd u0 {1,D} {3,S}
3 *5 Cd u0 {2,S} {4,D}
4 *6 Cd u0 {3,D} {7,S} {8,S}
5    H  u0 {1,S}
6 *7 Cd ux {1,S} {8,D}
7 *8 R  ux {4,S}
8 *9 Cd ux {4,S} {6,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzene_twoSub1",
    group = 
"""
1 *3 Cd u0 {2,D} {5,S} {6,S}
2 *4 Cd u0 {1,D} {3,S}
3 *5 Cd u0 {2,S} {4,D}
4 *6 Cd u0 {3,D} {7,S} {8,S}
5    H  u0 {1,S}
6 *7 Cd ux {1,S} {8,D}
7 *8 R  ux {4,S}
8 *9 Cd ux {4,S} {6,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzene_twoSub2",
    group = 
"""
1 *3 Cd u0 {2,D} {5,S} {6,S}
2 *4 Cd u0 {1,D} {3,S}
3 *5 Cd u0 {2,S} {4,D}
4 *6 Cd u0 {3,D} {7,S} {8,S}
5    H  u0 {1,S}
6 *7 Cd ux {1,S} {8,D}
7 *8 R  ux {4,S}
8 *9 Cd ux {4,S} {6,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzyl_isomer1",
    group = 
"""
1 C u0 {2,D}
2 C u0 {1,D} {3,S} {7,S}
3 C u0 {2,S} {4,D}
4 C u0 {3,D} {5,S}
5 C u1 {4,S} {6,S}
6 C u0 {5,S} {7,D}
7 C u0 {2,S} {6,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "benzyl_isomer2",
    group = 
"""
1 C u0 {2,D}
2 C u0 {1,D} {3,S} {7,S}
3 C u1 {2,S} {4,S}
4 C u0 {3,S} {5,D}
5 C u0 {4,D} {6,S}
6 C u0 {5,S} {7,D}
7 C u0 {2,S} {6,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "threeMemberedRing_2342",
    group = 
"""
1 *3 Cd u0 {2,D}
2 *4 Cd u0 {1,D} {3,S} {4,S}
3 *5 Cd u0 {2,S} {4,D}
4 *6 Cd u0 {2,S} {3,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "threeMemberedRing_3213",
    group = 
"""
1 *3 Cd u0 {2,D} {3,S}
2 *4 Cd u0 {1,D} {3,S}
3 *5 Cd u0 {1,S} {2,S} {4,D}
4 *6 Cd u0 {3,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

